### PR TITLE
Hake model edits

### PR DESCRIPTION
**Pull request by seananderson**
A series of edits to the hake model setups to bring them in line with the other species. Almost all work was on the hake EM. I have based the parameter estimation around the cod model. 

This isn't necessarily done yet or fully tested but it looks like there has been some other work happening on the hake models so I thought it would be good to get this merged into the master branch.

The matrices of numbers in the EM `.ctl` file are vertically aligned right now and I left them that way while we tweak the models.

The EM runs reasonably quickly (under 2 minutes). There's a little file `check.R` in the `hake-em` folder that I've been using for testing. It could be used for other models too.

### CODE REVIEW

**Comment by kellijohnson-NOAA** [comment]
In the EM, 2 is referenced as the first age mature, but the starter file uses 3+ to calculates summary biomass. I am not sure how this should be handled or if it is even an issue.

**Comment by seananderson** [comment]
Not sure about the issue you brought up, Kelli, but good catch.

Also not sure how this should be merged in given your commit to the master branch yesterday, @Kotkot 
https://github.com/ss3sim/growth_models/commit/a1638677b6efeeead503d417a25ff78dff2ee93c

Did you do something there we should incorporate into this branch before merging?

**Comment by Kotkot** [comment]
The recent commit to the master branch on 'hake' model came up when Juan and myself were trying to convert the hak-om model from length based selectivity to the age based selectivity.
We noticed that in the latter, the maturity curve (length based) was not completely asymptotic (by the size at Linf) and this was creating some problem in converting it to an age based maturity curve. 
--> in the end we still did it and created the 'hak_age_based' but we haven't pushed it as the mismatch bothered me. 

Then we had some email exchanges with Ian and Allan to talk about this issue and get their opinion on that. They said that slight modifications to the 'hak' model so that the maturity is more asymptotic would be fine. That is why I went ahead and created the "new" 'hake' model folders with the corresponding age based selectivity versions. 
--> so the differences between the 'hak-om' (taken from the master branch) and 'hake-om' are: 
- the parameter values for the maturity curve
- the presence of CPUE fleet
- the selectivity parameters adjusted for this new maturity curve.

So any modifications aside from these that Sean made is NOT included in this 'hake' model. 

On the topic of summary biomass vs first age mature, I don't think this is an issue. 
Summary biomass is just an output that the West coast assessment people put for their documents but is not a parameter as important as SSB for example. 
However, this raises the potential issue of whether we should REMOVE this first age mature value (put to zero or else) so that the maturity curve really stays the way we specified into the ctl file. This "first age mature" replaces any maturity value before this age to 0... so the curve might not be logistic anymore. This might be an issue or maybe not.

**Comment by seananderson** [comment]
But now there are `hak-om`, `hak-em`, `hake-om`, and `hake-em` folders in the master branch. The `hake...` folders conflict with the branch I was working in. Was this a mistake? The CPUE fleet should be in this pull request too. So, should I just keep the changes to the maturity curve in `hak-om` in the master branch and otherwise bring the changes from this pull request over to master?

**Pull request merged**
