### PR TITLE
Yelloweye

### PR DESCRIPTION
**Pull request by peterkuriyama**

### CODE REVIEW

**Comment by seananderson** [comment]
Not sure who's taking care of pull requests on this repository. Looks there are some conflicts in the `starter.ss` file here. I'm happy to merge this in if someone gives me the go ahead and tells me which `starter.ss` to pick (or which lines from each to pick).

**Comment by colemonnahan** [comment]
I propose we have @kellijohnson be the moderator for that repo.

**Comment by kellijohnson-NOAA** [comment]
So @seananderson do I now push the Delete branch? Not sure what the proper protocol is.

**Comment by seananderson** [comment]
Yes, you can delete the remote branch now. Probably no point to keeping a branch around unless we're going to continue developing in it. The pull request issue will remain.

**Pull request merged**
